apiVersion: v1
kind: Service
metadata:
  name: ng-debug-service-lb
spec:
  selector:
    app: ng-debug-lb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 31235
      name: ng-debug-port
  type: LoadBalancer
  