apiVersion: v1
kind: Pod
metadata:
  labels:
    app: my-busybox
  name: my-busybox
spec:
  containers:
    - image: busybox
      name: busybox
      command: ['sleep','60']
  dnsPolicy: ClusterFirst
  restartPolicy: Always