apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    myapp: our-nginx
  namespace: default
spec:
  containers:
    - name: Title
      image: nginx
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
