apiVersion: v1
kind: Service
metadata:
  name: headless-ng
spec:
  selector:
    app: ng-debug-node
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP
  clusterIP: None
  