apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ng-debug-ss
  labels:
    app: ng-debug-ss
spec:
  serviceName: headless-ng
  replicas: 3
  selector:
    matchLabels:
      app: ng-debug-ss
  template:
    metadata:
      name: ng-debug-ss
      labels:
        app: ng-debug-ss
    spec:
      containers:
        - name: ng-debug
          image: osmanyay/ng-debug:v1.0.0
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /usr/share/ss
              name: ng-vol1
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: ng-vol1
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
