apiVersion: v1
kind: Service
metadata:
  name: ng-debug-service
spec:
  selector:
    app: ng-debug
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      name: ng-debug-port
  type: ClusterIP
  