apiVersion: v1
kind: Service
metadata:
  name: ng-debug-service-node
spec:
  selector:
    app: ng-debug-node
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 31234
      name: ng-debug-port
  type: NodePort
  