apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
  labels:
    app: nginx-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-dep
  template:
    metadata:
      name: nginx-dep
      labels:
        app: nginx-dep
    spec:
      containers:
        - name: nginx-dep
          image: nginx:latest
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
      restartPolicy: Always