apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
  labels:
    app: nginx-dep
spec:
  replicas: 3
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: nginx-dep
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: nginx-dep
      labels:
        app: nginx-dep
    spec:
      containers:
        - name: nginx-dep
          image: nginx:1.24-alpine
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
      restartPolicy: Always